import {
  AlarmClock,
  Ban,
  Bell,
  Box,
  CalendarDays,
  ChartLine,
  Check,
  ChevronLeft,
  CircleMinus,
  CirclePlus,
  CircleQuestionMark,
  Clapperboard,
  Component,
  Cpu,
  Database,
  Diamond,
  Download,
  ExternalLink,
  Factory,
  FileDown,
  FileText,
  FolderCode,
  FolderSync,
  GitBranch,
  Globe,
  Hammer,
  HardDrive,
  History,
  Info,
  KeyRound,
  Layers,
  Layers2,
  LayoutDashboard,
  Link,
  ListTodo,
  MemoryStick,
  Milestone,
  Network,
  Pause,
  Play,
  Plus,
  RefreshCcw,
  Rocket,
  RotateCcwKey,
  Route,
  Save,
  Scissors,
  Search,
  SearchX,
  Server,
  Settings,
  Square,
  SquareStack,
  Tag,
  Tags,
  Terminal,
  Trash,
  Trash2,
  TriangleAlert,
  Unlink,
  User,
  X,
  Zap,
} from "lucide-react";

export const ICONS = {
  // RESOURCES
  Action: Clapperboard,
  Alerter: AlarmClock,
  Build: Hammer,
  Builder: Factory,
  Deployment: Rocket,
  Procedure: Route,
  Repo: GitBranch,
  Server,
  Stack: Layers,
  Swarm: Component,
  ResourceSync: FolderSync,
  ExportToml: FileDown,
  // PAGES
  Dashboard: LayoutDashboard,
  Terminal: Terminal,
  Schedule: CalendarDays,
  // DOCKER
  Container: Box,
  Network,
  Image: HardDrive,
  Volume: Database,
  Service: Layers2,
  Log: FileText,
  // SWARM
  SwarmNode: Diamond,
  SwarmStack: SquareStack,
  SwarmService: FolderCode,
  SwarmTask: ListTodo,
  SwarmConfig: Settings,
  SwarmSecret: KeyRound,
  // Device
  IP: Globe,
  Cpu,
  LoadAvg: ChartLine,
  Memory: MemoryStick,
  Disk: Database,
  // EXECUTIONS
  Deploy: Rocket,
  Destroy: Trash,
  Start: Play,
  Stop: Square,
  Restart: RefreshCcw,
  Pull: Download,
  Pause,
  Prune: Scissors,
  Refresh: RefreshCcw,
  // MISC
  User,
  Key: KeyRound,
  RotateKey: RotateCcwKey,
  Settings,
  System: Settings,
  Tag,
  Tags,
  Link,
  Unlink,
  ExternalLink,
  Alert: TriangleAlert,
  Update: Bell,
  Check: Check,
  Execution: Zap,
  History,
  Version: Milestone,
  Back: ChevronLeft,
  Calendar: CalendarDays,
  Search,
  Create: Plus,
  Delete: Trash2,
  Add: CirclePlus,
  Remove: CircleMinus,
  Clear: X,
  Save,
  Download,
  Info,
  Cancel: Ban,
  NotFound: SearchX,
  Unknown: CircleQuestionMark,
};
