[package]
name = "periphery_client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# local
komodo_client.workspace = true
# mogh
resolver_api.workspace = true
serror.workspace = true
# external
tokio-tungstenite.workspace = true
futures-util.workspace = true
serde_json.workspace = true
serde_qs.workspace = true
reqwest.workspace = true
tracing.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true