import {
  AlarmClock,
  Bell,
  Box,
  CalendarDays,
  ChevronLeft,
  CircleQuestionMark,
  Clapperboard,
  Component,
  Factory,
  FolderSync,
  GitBranch,
  Hammer,
  History,
  KeyRound,
  Layers,
  LayoutDashboard,
  Rocket,
  Route,
  Search,
  SearchX,
  Server,
  Settings,
  Terminal,
  TriangleAlert,
  User,
} from "lucide-react";

export const ICONS = {
  // RESOURCES
  Action: Clapperboard,
  Alerter: AlarmClock,
  Build: Hammer,
  Builder: Factory,
  Deployment: Rocket,
  Procedure: Route,
  Repo: GitBranch,
  Server,
  Stack: Layers,
  Swarm: Component,
  ResourceSync: FolderSync,
  // PAGES
  Dashboard: LayoutDashboard,
  Container: Box,
  Terminal: Terminal,
  Schedule: CalendarDays,
  // MISC
  User,
  Key: KeyRound,
  Settings,
  Alert: TriangleAlert,
  Update: Bell,
  History,
  Back: ChevronLeft,
  Search,
  NotFound: SearchX,
  Unknown: CircleQuestionMark,
};
