import {
  AlarmClock,
  Bell,
  Box,
  CalendarDays,
  Check,
  ChevronLeft,
  CircleQuestionMark,
  Clapperboard,
  Component,
  ExternalLink,
  Factory,
  FileDown,
  FolderSync,
  GitBranch,
  Hammer,
  HardDrive,
  History,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link,
  Milestone,
  Minus,
  Plus,
  Rocket,
  RotateCcwKey,
  Route,
  Save,
  Search,
  SearchX,
  Server,
  Settings,
  Tag,
  Terminal,
  TriangleAlert,
  Unlink,
  User,
  Zap,
} from "lucide-react";

export const ICONS = {
  // RESOURCES
  Action: Clapperboard,
  Alerter: AlarmClock,
  Build: Hammer,
  Builder: Factory,
  Deployment: Rocket,
  Procedure: Route,
  Repo: GitBranch,
  Server,
  Stack: Layers,
  Swarm: Component,
  ResourceSync: FolderSync,
  ExportToml: FileDown,
  // PAGES
  Dashboard: LayoutDashboard,
  Container: Box,
  Terminal: Terminal,
  Schedule: CalendarDays,
  // DOCKER
  Image: HardDrive,
  // MISC
  User,
  Key: KeyRound,
  RotateKey: RotateCcwKey,
  Settings,
  System: Settings,
  Tag,
  Link,
  Unlink,
  ExternalLink,
  Alert: TriangleAlert,
  Update: Bell,
  Check: Check,
  Execution: Zap,
  History,
  Version: Milestone,
  Back: ChevronLeft,
  Calendar: CalendarDays,
  Search,
  Create: Plus,
  Delete: Minus,
  Save: Save,
  NotFound: SearchX,
  Unknown: CircleQuestionMark,
};
